export const employeePortalKeys = {
  all: ['employee-portal'],
  leaveRequests: (status) => [...employeePortalKeys.all, 'leave-requests', status],
  leaveBalances: (year) => [...employeePortalKeys.all, 'leave-balances', year],
  leaveBalanceDetail: (leaveConfigurationId, year) => [
    ...employeePortalKeys.all,
    'leave-balance-detail',
    leaveConfigurationId,
    year,
  ],
  leaveCalendar: (year, month, filter) => [...employeePortalKeys.all, 'leave-calendar', year, month, filter],
  leaveTransactions: (date, filter, search) => [
    ...employeePortalKeys.all,
    'leave-transactions',
    date,
    filter,
    search ?? '',
  ],
  leavePreview: (params) => [...employeePortalKeys.all, 'leave-preview', params],
  holidayCalendar: (year) => [...employeePortalKeys.all, 'holiday-calendar', year],
  attendanceSummary: (year, month) => [...employeePortalKeys.all, 'attendance-summary', year, month],
  attendanceDays: (year, month) => [...employeePortalKeys.all, 'attendance-days', year, month],
  attendanceDay: (date) => [...employeePortalKeys.all, 'attendance-day', date],
  home: () => [...employeePortalKeys.all, 'home'],
  leaveTypes: () => [...employeePortalKeys.all, 'leave-types'],
  colleagues: (search) => [...employeePortalKeys.all, 'colleagues', search ?? ''],
  notifications: () => [...employeePortalKeys.all, 'notifications'],
  notificationUnreadCount: () => [...employeePortalKeys.all, 'notification-unread-count'],
  timesheetDay: (date) => [...employeePortalKeys.all, 'timesheet-day', date],
  timesheetReports: (granularity, from, to) => [
    ...employeePortalKeys.all,
    'timesheet-reports',
    granularity,
    from,
    to,
  ],
  timesheetReportEntries: (from, to) => [
    ...employeePortalKeys.all,
    'timesheet-report-entries',
    from,
    to,
  ],
  timesheetSettings: () => [...employeePortalKeys.all, 'timesheet-settings'],
  timesheetCategories: () => [...employeePortalKeys.all, 'timesheet-categories'],
};
